apiVersion: v1
kind: Pod
metadata:
  name: pod-with-sidecar
spec:
  volumes:
  - name: shared-logs 
    emptyDir: {}
  containers:

  # Main application container
  - name: app-container-postgres
    image: postgres # alpine is a simple Linux OS image
    env:
    - name: "POSTGRES_DB"
      value: "postgres"
    - name: "POSTGRES_USER"
      value: "postgres"
    - name: "POSTGRES_PASSWORD"
      value: "Siemens123"
    volumeMounts:
    - name: shared-logs
      mountPath: /var/lib/postgresql
    ports:
    - containerPort: 5432

  # Sidecar container
  - name: alpine1
    image: alpine
    ports:
      - containerPort: 4502
      
  - name: alpine2
    image: alpine
    ports:
      - containerPort: 4503
      
  - name: alpine3
    image: alpine
    ports:
      - containerPort: 4504    


