apiVersion: v1
kind: Pod
metadata:
  name: pod-with-sidecar
spec:
  volumes:
  - name: shared-logs 
    emptyDir: {}
  containers:

  # Main application container
  - name: app-container-postgres
    imagePullPolicy: IfNotPresent
    image: postgres # alpine is a simple Linux OS image
    env:
    - name: "POSTGRES_DB"
      value: "postgres"
    - name: "POSTGRES_USER"
      value: "postgres"
    - name: "POSTGRES_PASSWORD"
      value: "Siemens123"
    volumeMounts:
    - name: shared-logs
      mountPath: /var/lib/postgresql
    ports:
    - containerPort: 5432

  # Sidecar container
  - name: kpi-image-service
    imagePullPolicy: IfNotPresent
    image: kpi-image:latest 
    ports:
    - containerPort: 4502
  

  - name: asset-image-service
    imagePullPolicy: IfNotPresent
    image: asset-image:latest     
    ports:
    - containerPort: 4503  
      
  - name: data-image-service
    imagePullPolicy: IfNotPresent
    image: data-image:latest  
    
    ports:
    - containerPort: 4504 
