apiVersion: v1
kind: Pod
metadata:
  name: pod-with-sidecar
spec:
  volumes:
  - name: shared-logs 
    emptyDir: {}
  containers:

  # Main application container
  - name: app-container-postgres
    image: postgres # alpine is a simple Linux OS image
    env:
    - name: "POSTGRES_DB"
      value: "postgres"
    - name: "POSTGRES_USER"
      value: "postgres"
    - name: "POSTGRES_PASSWORD"
      value: "Siemens123"
    volumeMounts:
    - name: shared-logs
      mountPath: /var/lib/postgresql
    ports:
    - containerPort: 5432

  # Sidecar container
  - name: kpi-image
    image: kpi-image
    env:
    - name: "http_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "https_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "no_proxy"
      value: "localhost;127.0.0.1"
    - name: "DBSERVICETYPE"
      value: "postgres"
    - name: "DBSERVICE"
      value: "EdgeDatabase"  
    - name: "VCAP_SERVICES"
      value: "{"postgres":[{"name":"EdgeDatabase","credentials":{"name":"postgres","host":"database-service","port":"5432","username":"postgres","password":"Siemens123"}}]}"
    - name: "EXTENDED_ERRORS"
      value: "true"
    - name: "LOG_DEBUG_INFO"
      value: "true"
    ports:
    - containerPort: 4502
  
    

  - name: kpi-assets
    image: kpi-assets
    env:
    - name: "http_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "https_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "no_proxy"
      value: "localhost;127.0.0.1"
    - name: "DBSERVICETYPE"
      value: "postgres"
    - name: "DBSERVICE"
      value: "EdgeDatabase"  
    - name: "VCAP_SERVICES"
      value: "{"postgres":[{"name":"EdgeDatabase","credentials":{"name":"postgres","host":"database-service","port":"5432","username":"postgres","password":"Siemens123"}}]}"
    - name: "EXTENDED_ERRORS"
      value: "true"
    - name: "LOG_DEBUG_INFO"
      value: "true"
    ports:
    - containerPort: 4503  
      
  - name: kpi-data
    image: kpi-data
    env:
    - name: "http_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "https_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "no_proxy"
      value: "localhost;127.0.0.1"
    - name: "DBSERVICETYPE"
      value: "postgres"
    - name: "DBSERVICE"
      value: "EdgeDatabase"  
    - name: "VCAP_SERVICES"
      value: "{"postgres":[{"name":"EdgeDatabase","credentials":{"name":"postgres","host":"database-service","port":"5432","username":"postgres","password":"Siemens123"}}]}"
    - name: "EXTENDED_ERRORS"
      value: "true"
    - name: "LOG_DEBUG_INFO"
      value: "true"
    ports:
    - containerPort: 4504 
